// ─── APP STATE ────────────────────────────────────────────────────────────────
const AppState = (() => {
  let selectedId=ANIMALS[0].id;
  function getSelectedAnimal() { return ANIMALS.find(a=>a.id===selectedId)||ANIMALS[0]; }
  function selectAnimal(id) {
    selectedId=id;
    renderAnimalGrid(); renderAnimalDetail();
    ChartsModule.refreshAll(getSelectedAnimal());
    showSection('rebanho', document.querySelectorAll('.nav-btn')[1]);
  }
  return { get selectedAnimalId(){return selectedId;}, getSelectedAnimal, selectAnimal };
})();

// ─── RENDER FUNCTIONS ─────────────────────────────────────────────────────────
function renderTopMetrics(){ const healthy=ANIMALS.filter(a=>a.status==='ok').length,alerts=ANIMALS.filter(a=>a.status!=='ok').length,avg=(ANIMALS.reduce((s,a)=>s+a.score,0)/ANIMALS.length).toFixed(2); document.getElementById('topMetrics').innerHTML=[{val:ANIMALS.length,lbl:'Animais',color:'#1a1a1a'},{val:healthy,lbl:'Saudáveis',color:'#1D9E75'},{val:alerts,lbl:'Alertas',color:'#EF9F27'},{val:avg,lbl:'D/M* médio',color:'#1a1a1a'}].map(m=>`<div class="topbar-metric"><div class="topbar-metric-val" style="color:${m.color};">${m.val}</div><div class="topbar-metric-lbl">${m.lbl}</div></div>`).join(''); }

function renderAnimalGrid(){ document.getElementById('animalGrid').innerHTML=ANIMALS.map(a=>{ const c=Predictor.scoreColor(a.score),sl=a.status==='ok'?'Saudável':a.status==='warn'?'Atenção':'Crítico',bc=a.status==='ok'?'green':a.status==='warn'?'amber':'red'; return `<div class="animal-card ${AppState.selectedAnimalId===a.id?'selected':''}" onclick="AppState.selectAnimal(${a.id})"><div class="animal-avatar">${a.photo?`<img src="${a.photo}" alt="${a.name}">`:a.emoji}</div><div class="animal-name">${a.name}</div><div class="animal-id">${a.age} anos · ${a.local}</div><div style="text-align:center;margin:4px 0;"><span class="badge ${bc}">${sl}</span></div><div class="animal-score" style="color:${c};">${a.score.toFixed(2)}</div><div style="font-size:10px;color:#999;text-align:center;margin-top:2px;">Score D/M*</div><div class="score-bar"><div class="score-fill" style="width:${Math.min(a.score/1.5*100,100).toFixed(0)}%;background:${c};"></div></div></div>`; }).join(''); }

function renderAnimalDetail(){ const a=AppState.getSelectedAnimal(),risk=Predictor.computeRisk(a),desc=Predictor.describeAnimal(a),el=document.getElementById('animalDetail'); el.style.display='block'; el.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:16px;"><div style="display:flex;align-items:center;gap:12px;"><div style="font-size:40px;">${a.emoji}</div><div><div style="font-size:18px;font-weight:700;">${a.name}</div><div style="font-size:13px;color:#666;">${a.local} · ${a.country} · Lactação ${a.lactation}</div></div></div><div style="text-align:right;"><div style="font-size:28px;font-weight:700;color:${desc.riskColor};">${a.score.toFixed(2)}</div><span class="badge ${a.status==='ok'?'green':a.status==='warn'?'amber':'red'}">${desc.riskLevel}</span></div></div><div class="detail-grid"><div class="detail-item"><div class="detail-label">Peso</div><div class="detail-value">${a.weight}</div></div><div class="detail-item"><div class="detail-label">Temperatura</div><div class="detail-value" style="color:#D85A30;">${a.temp}</div></div><div class="detail-item"><div class="detail-label">Ruminação</div><div class="detail-value">${a.rumination}</div></div><div class="detail-item"><div class="detail-label">σ-field (24m)</div><div class="detail-value" style="color:#7F77DD;">${a.sigma.toFixed(2)}</div></div><div class="detail-item"><div class="detail-label">φ-field (6m)</div><div class="detail-value" style="color:#D85A30;">${a.phi.toFixed(2)}</div></div><div class="detail-item"><div class="detail-label">Previsão</div><div class="detail-value" style="font-size:12px;color:#1D9E75;">${desc.leadTime}</div></div></div><div style="margin-top:12px;padding:12px;background:#E1F5EE;border-radius:8px;font-size:13px;color:#0F6E56;">💡 <strong>Recomendação:</strong> ${desc.recommendation}</div>`; }

function renderModules(){ document.getElementById('modulesList').innerHTML=MODULES.map(m=>`<div class="module-item"><div class="module-num">${m.num}</div><div style="flex:1;"><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;"><div class="module-name">${m.name}</div><span class="badge blue">${m.field}</span><span class="badge ${m.status==='ok'?'green':'amber'}">${m.coverage}% cobertura</span></div><div class="module-desc">${m.desc}</div><div style="height:4px;border-radius:2px;background:#f0f0f0;margin-top:8px;overflow:hidden;"><div style="height:100%;width:${m.coverage}%;background:${m.status==='ok'?'#1D9E75':'#EF9F27'};border-radius:2px;"></div></div></div></div>`).join(''); setTimeout(()=>ChartsModule.buildRadar(),100); }

function renderMotorPreditivo(){ document.getElementById('motorGrid').innerHTML=`
  <div class="motor-card"><div class="motor-card-title">Índice de bem-estar composto</div><div style="padding:10px;background:#E1F5EE;border-radius:8px;"><div style="font-size:11px;color:#0F6E56;margin-bottom:6px;">Parâmetros monitorados</div>${ANIMALS.map(a=>`<div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;"><div style="font-size:12px;font-weight:600;flex:1;">${a.name}</div><div style="height:6px;flex:2;border-radius:3px;background:#C0DD97;overflow:hidden;"><div style="height:100%;width:${(a.score/1.5*100).toFixed(0)}%;background:${Predictor.scoreColor(a.score)};border-radius:3px;"></div></div><div style="font-size:12px;font-weight:700;color:${Predictor.scoreColor(a.score)};min-width:32px;text-align:right;">${a.score.toFixed(2)}</div></div>`).join('')}</div><div style="font-size:11px;color:#0F6E56;margin-top:8px;">Atualização contínua via sensores</div></div>
  <div class="motor-card"><div class="motor-card-title">Limiares de alerta</div><div class="motor-threshold"><div class="threshold-item" style="background:#E1F5EE;"><div class="threshold-val">D/M* &lt; 0.3</div><div class="threshold-label" style="color:#0F6E56;">INATIVO</div></div><div class="threshold-item" style="background:#FAEEDA;"><div class="threshold-val">0.3 – 0.8</div><div class="threshold-label" style="color:#854F0B;">MONITORAR</div></div><div class="threshold-item" style="background:#FAECE7;"><div class="threshold-val">0.8 – 1.2</div><div class="threshold-label" style="color:#993C1D;">AGIR</div></div><div class="threshold-item" style="background:#FCEBEB;"><div class="threshold-val">D/M* &gt; 1.2</div><div class="threshold-label" style="color:#A32D2D;">CRÍTICO</div></div></div></div>
  <div class="motor-card"><div class="motor-card-title">Memória de longo prazo (σ)</div><div style="padding:10px;background:#F1EFE8;border-radius:8px;">${ANIMALS.map(a=>`<div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;"><div style="font-size:11px;color:#666;flex:1;">${a.name.split(' ')[0]}</div><div style="height:5px;flex:2;border-radius:3px;background:#D3D1C7;overflow:hidden;"><div style="height:100%;width:${(a.sigma*100).toFixed(0)}%;background:#7F77DD;border-radius:3px;"></div></div><div style="font-size:11px;font-weight:600;color:#7F77DD;min-width:30px;text-align:right;">${a.sigma.toFixed(2)}</div></div>`).join('')}<div style="font-size:10px;color:#999;margin-top:4px;">Janela: 24 meses</div></div></div>
  <div class="motor-card"><div class="motor-card-title">Memória de curto prazo (φ)</div><div style="padding:10px;background:#F1EFE8;border-radius:8px;">${ANIMALS.map(a=>`<div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;"><div style="font-size:11px;color:#666;flex:1;">${a.name.split(' ')[0]}</div><div style="height:5px;flex:2;border-radius:3px;background:#D3D1C7;overflow:hidden;"><div style="height:100%;width:${(a.phi*100).toFixed(0)}%;background:#D85A30;border-radius:3px;"></div></div><div style="font-size:11px;font-weight:600;color:#D85A30;min-width:30px;text-align:right;">${a.phi.toFixed(2)}</div></div>`).join('')}<div style="font-size:10px;color:#999;margin-top:4px;">Janela: 6 meses · ecos de choque</div></div></div>
  <div class="motor-card"><div class="motor-card-title">Estado do rebanho — agora</div><div style="display:flex;flex-direction:column;gap:8px;margin-top:4px;">${ANIMALS.map(a=>{ const al=Predictor.alertLevel(Predictor.computeRisk(a).ratio); return `<div style="display:flex;align-items:center;gap:10px;padding:8px 10px;background:${al.bg};border-radius:8px;"><div style="font-size:12px;font-weight:600;flex:1;">${a.emoji} ${a.name}</div><div style="font-size:12px;font-weight:700;color:${al.color};">${al.level}</div></div>`; }).join('')}</div></div>
  <div class="motor-card"><div class="motor-card-title">Antecedência de previsão</div><div style="display:flex;flex-direction:column;gap:8px;margin-top:4px;">${ANIMALS.map(a=>`<div style="display:flex;align-items:center;justify-content:space-between;padding:8px 10px;background:#F7F6F3;border-radius:8px;border:1px solid rgba(0,0,0,0.06);"><div style="font-size:12px;font-weight:600;">${a.name.split(' ')[0]}</div><div style="font-size:11px;color:#1D9E75;font-weight:600;">${Predictor.leadTime(a.sigma)}</div></div>`).join('')}</div></div>`; }

// ─── NAVEGAÇÃO ────────────────────────────────────────────────────────────────
function showSection(id, btn) {
  document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));
  document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));
  document.getElementById('section-'+id).classList.add('active');
  if(btn) btn.classList.add('active');
  if(id==='graficos') setTimeout(()=>{ const a=AppState.getSelectedAnimal(); ChartsModule.buildBeforeAfter(); ChartsModule.buildMilk(a); ChartsModule.buildDisease(); ChartsModule.buildCost(); },100);
  if(id==='rebanho') renderAnimalDetail();
}
function switchChartTab(tabId,el){ document.querySelectorAll('.chart-tab').forEach(t=>t.classList.remove('active')); document.querySelectorAll('.chart-tab-content').forEach(c=>c.classList.remove('active')); el.classList.add('active'); document.getElementById('ctab-'+tabId).classList.add('active'); const a=AppState.getSelectedAnimal(); setTimeout(()=>{ if(tabId==='antes-depois'){ChartsModule.buildBeforeAfter();ChartsModule.buildMilk(a);ChartsModule.buildDisease();ChartsModule.buildCost();}if(tabId==='tempo-real'){ChartsModule.buildRealtime();ChartsModule.buildTemp(a);ChartsModule.updateSensorBars(a);}if(tabId==='evolucao'){ChartsModule.buildEvolution();ChartsModule.buildMemory(a);ChartsModule.buildRumination(a);} },80); }

// ─── MODAL ────────────────────────────────────────────────────────────────────
function openAddModal()  { document.getElementById('addModal').style.display='flex'; }
function closeAddModal() { document.getElementById('addModal').style.display='none'; }
function handlePhoto(e){ const file=e.target.files[0]; if(!file) return; const r=new FileReader(); r.onload=ev=>{ const area=document.getElementById('uploadArea'); area.innerHTML=`<img src="${ev.target.result}" style="width:80px;height:80px;border-radius:50%;object-fit:cover;"><br><span style="font-size:11px;color:#666;">Foto carregada ✓</span>`; area._photo=ev.target.result; }; r.readAsDataURL(file); }
function saveAnimal(){ const name=document.getElementById('fName').value||`Vaca #${ANIMALS.length+1}`,age=parseInt(document.getElementById('fAge').value)||1,local=document.getElementById('fLocal').value||'Pasto A',score=parseFloat(document.getElementById('fScore').value)||0.3,weight=document.getElementById('fWeight').value?document.getElementById('fWeight').value+'kg':'500kg',lact=document.getElementById('fLact').value||'1ª',photo=document.getElementById('uploadArea')._photo||null; const newA={ id:Date.now(),name,emoji:'🐄',age,local,country:'Portugal',score,scoreBefore:+(score+0.2+Math.random()*0.2).toFixed(2),status:Predictor.statusFromScore(score),lat:40.5+(Math.random()-0.5)*0.5,lon:-8.3+(Math.random()-0.5)*0.5,lactation:lact,weight,temp:'38.5°C',rumination:'Normal',sigma:+(score*0.8).toFixed(2),phi:+(score*0.5).toFixed(2),photo,tempHistory:Array(24).fill(38.4).map(v=>+(v+Math.random()*0.5).toFixed(1)),milkHistory:Array(12).fill(16).map((v,i)=>+(v+i*0.2+Math.random()).toFixed(1)),sigmaHistory:Array(12).fill(score).map(v=>+(v+Math.random()*0.1-0.05).toFixed(2)),phiHistory:Array(12).fill(score*0.6).map(v=>+(v+Math.random()*0.08-0.04).toFixed(2)),ruminHistory:Array(12).fill(40).map(v=>Math.floor(v+Math.random()*10)) }; ANIMALS.push(newA); closeAddModal(); ['fName','fAge','fLocal','fScore','fWeight','fLact'].forEach(id=>{document.getElementById(id).value='';}); document.getElementById('uploadArea').innerHTML='📷 Clique para carregar foto do animal<input type="file" id="photoInput" accept="image/*" style="display:none" onchange="handlePhoto(event)">'; renderTopMetrics(); renderAnimalGrid(); MapModule.drawAnimals(); AppState.selectAnimal(newA.id); }

// ─── INIT ─────────────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  renderTopMetrics();
  renderAnimalGrid();
  MapModule.init();
  renderModules();
  renderMotorPreditivo();
  AlertsModule.render();
  ChartsModule.startRealtime(AppState.getSelectedAnimal.bind(AppState));
  setTimeout(()=>{ ChartsModule.buildBeforeAfter(); ChartsModule.buildMilk(AppState.getSelectedAnimal()); ChartsModule.buildDisease(); ChartsModule.buildCost(); },200);
});
