// ─── CHARTS ───────────────────────────────────────────────────────────────────
const ChartsModule = (() => {
  const charts={};
  const M6=['Nov','Dez','Jan','Fev','Mar','Abr'], M12=['Mai','Jun','Jul','Ago','Set','Out','Nov','Dez','Jan','Fev','Mar','Abr'];
  const H24=Array.from({length:24},(_,i)=>`${i}h`);
  let timeRange='6m', rtData=Array(24).fill(null).map(()=>+(0.25+Math.random()*0.35).toFixed(2)), rtInterval=null;
  const base={ responsive:true, maintainAspectRatio:false, plugins:{ legend:{display:false}, tooltip:{backgroundColor:'#fff',titleColor:'#222',bodyColor:'#555',borderColor:'#ddd',borderWidth:1,padding:10} }, scales:{ x:{grid:{display:false},ticks:{font:{size:10},color:'#999'}}, y:{grid:{color:'rgba(0,0,0,0.04)'},ticks:{font:{size:10},color:'#999'}} } };
  function mk(id,cfg){ const el=document.getElementById(id); if(!el) return null; if(charts[id]) charts[id].destroy(); charts[id]=new Chart(el.getContext('2d'),cfg); return charts[id]; }
  function buildBeforeAfter(){ mk('chartBeforeAfter',{type:'bar',data:{labels:ANIMALS.map(a=>a.name.split(' ')[0]),datasets:[{label:'Antes',data:ANIMALS.map(a=>a.scoreBefore),backgroundColor:'#F09595',borderRadius:5,borderSkipped:false},{label:'Depois (BoviWatch)',data:ANIMALS.map(a=>a.score),backgroundColor:'#5DCAA5',borderRadius:5,borderSkipped:false}]},options:{...base,plugins:{...base.plugins,legend:{display:true,labels:{font:{size:10},boxWidth:12,color:'#666'}}},scales:{...base.scales,y:{...base.scales.y,min:0,max:1.5}}}}); }
  function buildMilk(a){ const ss=timeRange==='6m'?6:0,lb=timeRange==='6m'?M6:M12; mk('chartMilk',{type:'line',data:{labels:lb,datasets:[{label:'Sem sistema',data:a.milkHistory.slice(ss).map(v=>+(v*0.88).toFixed(1)),borderColor:'#F09595',backgroundColor:'rgba(240,149,149,0.08)',tension:0.4,fill:true,pointRadius:3},{label:'Com BoviWatch',data:a.milkHistory.slice(ss),borderColor:'#1D9E75',backgroundColor:'rgba(29,158,117,0.08)',tension:0.4,fill:true,pointRadius:3}]},options:{...base,plugins:{...base.plugins,legend:{display:true,labels:{font:{size:10},boxWidth:12,color:'#666'}}}}}); }
  function buildDisease(){ mk('chartDisease',{type:'bar',data:{labels:M12,datasets:[{label:'Sem monitoramento',data:[3,4,3,5,4,3,2,2,1,1,1,1],backgroundColor:'#F09595',borderRadius:4,borderSkipped:false},{label:'Com BoviWatch',data:[3,4,3,5,4,3,1,1,0,1,0,0],backgroundColor:'#5DCAA5',borderRadius:4,borderSkipped:false}]},options:{...base,plugins:{...base.plugins,legend:{display:true,labels:{font:{size:10},boxWidth:12,color:'#666'}}},scales:{...base.scales,y:{...base.scales.y,min:0,max:6}}}}); }
  function buildCost(){ mk('chartCost',{type:'line',data:{labels:M12,datasets:[{label:'Sem sistema (€/animal)',data:[85,88,90,92,89,91,88,86,84,82,80,79],borderColor:'#F09595',backgroundColor:'rgba(240,149,149,0.08)',tension:0.4,fill:true,pointRadius:3},{label:'Com BoviWatch (€/animal)',data:[85,88,90,92,89,85,78,72,68,65,63,61],borderColor:'#1D9E75',backgroundColor:'rgba(29,158,117,0.08)',tension:0.4,fill:true,pointRadius:3}]},options:{...base,plugins:{...base.plugins,legend:{display:true,labels:{font:{size:10},boxWidth:12,color:'#666'}}}}}); }
  function buildRealtime(){ const lb=Array(24).fill('').map((_,i)=>i===23?'agora':i%4===0?(23-i)+'s atrás':''); mk('chartRealtime',{type:'line',data:{labels:lb,datasets:[{label:'Score D/M*',data:[...rtData],borderColor:'#1D9E75',backgroundColor:'rgba(29,158,117,0.06)',tension:0.4,fill:true,pointRadius:2},{label:'Limiar atenção (0.8)',data:Array(24).fill(0.8),borderColor:'#EF9F27',borderDash:[5,5],pointRadius:0,fill:false},{label:'Limiar crítico (1.2)',data:Array(24).fill(1.2),borderColor:'#E24B4A',borderDash:[5,5],pointRadius:0,fill:false}]},options:{...base,animation:{duration:300},plugins:{...base.plugins,legend:{display:true,labels:{font:{size:10},boxWidth:12,color:'#666'}}},scales:{...base.scales,y:{...base.scales.y,min:0,max:1.5}}}}); }
  function buildTemp(a){ mk('chartTemp',{type:'line',data:{labels:H24,datasets:[{label:'Temperatura (°C)',data:a.tempHistory,borderColor:'#D85A30',backgroundColor:'rgba(216,90,48,0.06)',tension:0.4,fill:true,pointRadius:2},{label:'Limiar normal (39°C)',data:Array(24).fill(39),borderColor:'#E24B4A',borderDash:[4,4],pointRadius:0,fill:false}]},options:{...base,plugins:{...base.plugins,legend:{display:true,labels:{font:{size:10},boxWidth:12,color:'#666'}}},scales:{...base.scales,y:{...base.scales.y,min:37.5,max:40.5}}}}); }
  function buildEvolution(){ const ss=timeRange==='6m'?6:0,lb=timeRange==='6m'?M6:M12; mk('chartEvolution',{type:'line',data:{labels:lb,datasets:ANIMALS.map(a=>({label:a.name.split(' ')[0],data:a.sigmaHistory.slice(ss),borderColor:Predictor.scoreColor(a.score),backgroundColor:'transparent',tension:0.4,pointRadius:3,borderWidth:AppState.selectedAnimalId===a.id?3:1.5}))},options:{...base,plugins:{...base.plugins,legend:{display:true,labels:{font:{size:10},boxWidth:12,color:'#666'}}},scales:{...base.scales,y:{...base.scales.y,min:0,max:1}}}}); }
  function buildMemory(a){ const ss=timeRange==='6m'?6:0,lb=timeRange==='6m'?M6:M12; mk('chartMemory',{type:'line',data:{labels:lb,datasets:[{label:'σ (memória longa 24m)',data:a.sigmaHistory.slice(ss),borderColor:'#7F77DD',backgroundColor:'rgba(127,119,221,0.07)',tension:0.4,fill:true,pointRadius:3},{label:'φ (memória curta 6m)',data:a.phiHistory.slice(ss),borderColor:'#D85A30',backgroundColor:'rgba(216,90,48,0.05)',tension:0.4,fill:true,pointRadius:3}]},options:{...base,plugins:{...base.plugins,legend:{display:true,labels:{font:{size:10},boxWidth:12,color:'#666'}}},scales:{...base.scales,y:{...base.scales.y,min:0,max:0.9}}}}); }
  function buildRumination(a){ const ss=timeRange==='6m'?6:0,lb=timeRange==='6m'?M6:M12; mk('chartRumination',{type:'bar',data:{labels:lb,datasets:ANIMALS.map(a=>({label:a.name.split(' ')[0],data:a.ruminHistory.slice(ss),backgroundColor:Predictor.scoreColor(a.score)+'66',borderColor:Predictor.scoreColor(a.score),borderWidth:1,borderRadius:4}))},options:{...base,plugins:{...base.plugins,legend:{display:true,labels:{font:{size:10},boxWidth:12,color:'#666'}}},scales:{...base.scales,y:{...base.scales.y,min:0,max:70}}}}); }
  function buildRadar(){ mk('chartRadar',{type:'radar',data:{labels:MODULES.map(m=>`M${m.num}`),datasets:[{label:'BoviWatch',data:MODULES.map(m=>m.coverage),borderColor:'#1D9E75',backgroundColor:'rgba(29,158,117,0.15)',pointBackgroundColor:'#1D9E75',pointRadius:4},{label:'Requisito InoCrowd',data:Array(7).fill(100),borderColor:'#B5D4F4',backgroundColor:'rgba(181,212,244,0.06)',pointBackgroundColor:'#378ADD',pointRadius:3,borderDash:[4,4]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,labels:{font:{size:10},boxWidth:12,color:'#666'}}},scales:{r:{grid:{color:'rgba(0,0,0,0.06)'},ticks:{display:false},pointLabels:{font:{size:11},color:'#666'},min:0,max:100}}}}); }
  function tickRealtime(getAnimal){ const last=rtData[rtData.length-1],next=Predictor.simulateSensor(last,0.06); rtData.shift(); rtData.push(next); if(charts['chartRealtime']){charts['chartRealtime'].data.datasets[0].data=[...rtData];charts['chartRealtime'].update('none');} updateSensorBars(getAnimal()); const cl=document.getElementById('rtClock'); if(cl) cl.textContent=new Date().toLocaleTimeString('pt-PT'); }
  function updateSensorBars(a){ const el=document.getElementById('sensorBars'); if(!el||!a) return; const sensors=[{label:'Score D/M*',val:rtData[rtData.length-1].toFixed(2),pct:rtData[rtData.length-1]/1.5,color:'#1D9E75'},{label:'Temperatura',val:(38+Math.random()*1.3).toFixed(1)+'°C',pct:0.55+Math.random()*0.25,color:'#D85A30'},{label:'Ruminação',val:Math.floor(35+Math.random()*25)+'min/h',pct:0.60+Math.random()*0.20,color:'#1D9E75'},{label:'Actividade',val:Math.floor(55+Math.random()*35)+'%',pct:0.55+Math.random()*0.35,color:'#7F77DD'},{label:'σ-field',val:a.sigma.toFixed(2),pct:a.sigma,color:'#7F77DD'},{label:'φ-field',val:a.phi.toFixed(2),pct:a.phi,color:'#D85A30'}]; el.innerHTML=sensors.map(s=>`<div class="sensor-row"><span class="sensor-label">${s.label}</span><div class="sensor-bar"><div class="sensor-fill" style="width:${Math.min(s.pct*100,100).toFixed(0)}%;background:${s.color};"></div></div><span class="sensor-val" style="color:${s.color};">${s.val}</span></div>`).join(''); }
  function setTimeRange(r){ timeRange=r; }
  function refreshAll(a){ const cur=document.querySelector('.chart-tab-content.active'); if(!cur) return; const id=cur.id; if(id==='ctab-antes-depois'){buildBeforeAfter();buildMilk(a);buildDisease();buildCost();}else if(id==='ctab-tempo-real'){buildRealtime();buildTemp(a);updateSensorBars(a);}else if(id==='ctab-evolucao'){buildEvolution();buildMemory(a);buildRumination(a);} }
  function startRealtime(getAnimal){ if(rtInterval) clearInterval(rtInterval); rtInterval=setInterval(()=>{ const cur=document.querySelector('.chart-tab-content.active'); if(cur&&cur.id==='ctab-tempo-real') tickRealtime(getAnimal); },3000); }
  return { buildBeforeAfter, buildMilk, buildDisease, buildCost, buildRealtime, buildTemp, buildEvolution, buildMemory, buildRumination, buildRadar, setTimeRange, refreshAll, startRealtime, updateSensorBars };
})();

function setTimeRange(r,el){ ChartsModule.setTimeRange(r); document.querySelectorAll('.time-btn').forEach(b=>b.classList.remove('active')); el.classList.add('active'); const a=AppState.getSelectedAnimal(); ChartsModule.buildEvolution(); ChartsModule.buildMemory(a); ChartsModule.buildMilk(a); ChartsModule.buildRumination(a); }

